#Sonata Admin Bundle
admin_login:
    pattern:  /admin
    defaults: { _controller: SonataAdminBundle:Core:dashboard }

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

soanata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin