admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

quran:
    resource: "@QuranBundle/Resources/config/routing.yml"
    prefix:   /



